"""Generator Agent - Creates Python API test code using pytest and requests."""

from crewai import Agent, LLM

from src.config.settings import get_settings


def create_generator_agent() -> Agent:
    """Create the Generator Agent that writes API test code.
    
    This agent is responsible for:
    - Generating well-structured pytest API tests
    - Implementing authentication flows (OAuth2, Basic Auth)
    - Creating request payloads and headers
    - Writing comprehensive assertions
    - Adding proper error handling and SSL configuration
    """
    settings = get_settings()
    
    llm = LLM(
        model=settings.ollama.get_model_string(),
        base_url=settings.ollama.base_url,
        temperature=settings.ollama.temperature,
    )
    
    return Agent(
        role="API Test Code Generator",
        goal="""Generate clean, well-structured, and maintainable Python API 
        test code using pytest and requests library. Follow best practices 
        for API testing including proper authentication, error handling, 
        and comprehensive assertions.""",
        backstory="""You are an expert Python developer specializing in API 
        test automation. You write clean, readable code that follows PEP 8 
        style guidelines. You have deep expertise with the requests library, 
        pytest fixtures, and API testing patterns. You know how to implement 
        OAuth2 authentication flows, handle SSL certificates, structure test 
        classes for API testing, and write meaningful assertions for response 
        validation. You always add proper docstrings, error handling, and 
        debug output for troubleshooting.""",
        llm=llm,
        verbose=settings.verbose,
        allow_delegation=False,
        memory=True,
    )


# Generation guidelines for the agent
GENERATOR_GUIDELINES = """
## API Test File Structure

```python
\"\"\"API Test module for [Feature Name].

Auto-generated by AI Test Case Generator.
API Endpoint: [Base URL]
\"\"\"

import pytest
import requests
import json


class TestAPIFeatureName:
    \"\"\"API Test cases for [Feature Name].\"\"\"
    
    # Configuration
    BASE_URL = "https://api.example.com"
    TOKEN_URL = "https://auth.example.com/oauth2/token"
    
    @pytest.fixture(autouse=True)
    def setup(self):
        \"\"\"Setup - obtain authentication token.\"\"\"
        self.session = requests.Session()
        self.session.verify = False  # For self-signed certs
        
        # Suppress SSL warnings
        import urllib3
        urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
        
        # Get OAuth2 token
        self.access_token = self._get_access_token()
        self.headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {self.access_token}"
        }
        
        yield
        self.session.close()
    
    def _get_access_token(self) -> str:
        \"\"\"Obtain OAuth2 access token.\"\"\"
        response = self.session.post(
            self.TOKEN_URL,
            data={"grant_type": "client_credentials", "scope": "full"},
            auth=("username", "password"),
            verify=False
        )
        return response.json().get("access_token")
    
    def get_base_payload(self) -> dict:
        \"\"\"Return base payload for API requests.\"\"\"
        return {...}
    
    @pytest.mark.positive
    def test_api_scenario_name(self):
        \"\"\"Test description with Given-When-Then.\"\"\"
        # Given - Setup
        payload = self.get_base_payload()
        
        # When - API Call
        response = self.session.post(
            f"{self.BASE_URL}/endpoint",
            json=payload,
            headers=self.headers,
            verify=False
        )
        
        # Then - Assertions
        assert response.status_code in [200, 201]
        data = response.json()
        assert "expected_field" in data
```

## Code Generation Rules

1. **Imports**: requests, pytest, json, urllib3
2. **Class Names**: PascalCase, start with "Test"
3. **Method Names**: snake_case, start with "test_"
4. **Fixtures**: Use autouse=True for setup
5. **SSL**: Always include verify=False for self-signed certs
6. **Auth**: Implement OAuth2 token flow in _get_access_token()
7. **Assertions**: Use assert with descriptive messages
8. **Debug Output**: Add print statements for troubleshooting
9. **Docstrings**: Include Given-When-Then in test docstrings
"""
