"""API Test module for Create Policy API - Description Field Validation.

Auto-generated by AI Test Case Generator.
API Endpoint: POST https://uapautomation-uap.cyberark-everest-pre-prod.cloud/api/policies

Authentication Flow:
1. Obtain OAuth2 token from CyberArk Identity
2. Use Bearer token for API requests
"""

import pytest
import requests
import json


class TestCreatePolicyDescriptionValidation:
    """API Test cases for Create Policy - Description Field Validation."""
    
    # Token API Configuration
    TOKEN_URL = "https://aog5018.id.integration-cyberark.cloud/oauth2/token/scadev"
    TOKEN_USERNAME = "serviceuserapr@cyberark.cloud.43204"
    TOKEN_PASSWORD = "Cyber@123"
    
    # Policy API Configuration
    API_BASE_URL = "https://uapautomation-uap.cyberark-everest-pre-prod.cloud/api"
    ENDPOINT = "/policies"
    
    @pytest.fixture(autouse=True)
    def setup(self):
        """Setup for each test - obtain OAuth2 token."""
        self.session = requests.Session()
        # Disable SSL verification for self-signed certificates
        self.session.verify = False
        
        # Suppress InsecureRequestWarning
        import urllib3
        urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
        
        # Get OAuth2 token
        self.access_token = self._get_access_token()
        
        # Set headers with Bearer token
        self.headers = {
            "Content-Type": "application/json",
            "Accept": "application/json",
            "Authorization": f"Bearer {self.access_token}"
        }
        
        yield
        self.session.close()
    
    def _get_access_token(self) -> str:
        """Obtain OAuth2 access token from CyberArk Identity.
        
        Token Body: {"grant_type": "client_credentials", "scope": "full"}
        
        Returns:
            Access token string
        """
        token_payload = {
            "grant_type": "client_credentials",
            "scope": "full"
        }
        
        response = self.session.post(
            self.TOKEN_URL,
            data=token_payload,
            auth=(self.TOKEN_USERNAME, self.TOKEN_PASSWORD),
            headers={"Content-Type": "application/x-www-form-urlencoded"},
            verify=False
        )
        
        if response.status_code != 200:
            pytest.fail(f"Failed to get token: {response.status_code} - {response.text}")
        
        token_data = response.json()
        return token_data.get("access_token")
    
    def get_base_payload(self) -> dict:
        """Return the base payload for Create Policy API."""
        return {
            "metadata": {
                "policyId": None,
                "name": "ravish-test-21",
                "description": "test",
                "status": {
                    "status": "Active",
                    "statusCode": None,
                    "statusDescription": None
                },
                "timeFrame": {
                    "fromTime": None,
                    "toTime": None
                },
                "policyEntitlement": {
                    "targetCategory": "Cloud console",
                    "locationType": "AWS",
                    "policyType": "Recurring"
                },
                "policyTags": [],
                "timeZone": "Asia/Calcutta"
            },
            "conditions": {
                "accessWindow": {
                    "timeZone": "Asia/Calcutta",
                    "daysOfTheWeek": [0, 1, 2, 3, 4, 5, 6]
                },
                "maxSessionDuration": 1
            },
            "targets": {
                "targets": [
                    {
                        "roleId": "arn:aws:iam::103162528131:role/AWXAccessRoleAccess",
                        "workspaceId": "103162528131",
                        "roleName": "AWXAccessRoleAccess",
                        "workspaceName": "DEV1",
                        "description": None
                    }
                ]
            },
            "principals": [
                {
                    "id": "d4c322fc-931c-4c1c-9a40-2e8bae17f494",
                    "name": "au_tony_1_sca_uap@cyberark.cloud.43204",
                    "displayName": "au_tony_1_sca_uap",
                    "sourceDirectoryName": "CyberArk Cloud Directory",
                    "sourceDirectoryId": "09B9A9B0-6CE8-465F-AB03-65766D33B05E",
                    "type": "USER",
                    "role": 1
                }
            ],
            "delegation_classification": "Unrestricted"
        }
    
    # ==================== POSITIVE TEST CASE ====================
    
    @pytest.mark.positive
    @pytest.mark.description
    @pytest.mark.validation
    def test_successfully_create_policy_with_valid_description_string_under_200_chars(self):
        """Verify policy creation succeeds with valid string description under 200 chars.
        
        Scenario: Successfully create policy with valid description (string, under 200 chars)
          Given the user obtains OAuth2 token from the token endpoint
          And the policy payload has description "Valid test policy description"
          When the user sends a POST request to "/policies" with valid payload
          Then the response status code should be 200 or 201
          And the response should contain the created policy details
        """
        # Given - the policy payload has description "Valid test policy description"
        payload = self.get_base_payload()
        payload["metadata"]["description"] = "Valid test policy description"
        
        # When - the user sends a POST request to "/policies" with valid payload
        response = self.session.post(
            f"{self.API_BASE_URL}{self.ENDPOINT}",
            json=payload,
            headers=self.headers,
            verify=False
        )
        
        # Debug output
        print(f"\n[DEBUG] Response Status: {response.status_code}")
        print(f"[DEBUG] Response Body: {response.text[:500] if response.text else 'Empty'}")
        
        # Then - the response status code should be 200 or 201
        assert response.status_code in [200, 201], \
            f"Expected 200/201, got {response.status_code}: {response.text}"
        
        # And - the response should contain the created policy details
        if response.headers.get('content-type', '').startswith('application/json'):
            response_data = response.json()
            assert response_data is not None, "Response should contain policy data"
            print(f"[DEBUG] Policy created successfully: {json.dumps(response_data, indent=2)[:500]}")

    # ==================== NEGATIVE TEST CASE ====================
    
    @pytest.mark.negative
    @pytest.mark.description
    @pytest.mark.null_validation
    def test_fail_to_create_policy_when_description_is_null(self):
        """Verify policy creation fails when description is null.
        
        Scenario: Fail to create policy when description is null
          Given the user obtains OAuth2 token from the token endpoint
          And the policy payload has description as null
          When the user sends a POST request to "/policies" with the payload
          Then the response status code should be 400
          And the response should contain an error message about invalid description
          And no policy should be created
        """
        # Given - the policy payload has description as null
        payload = self.get_base_payload()
        payload["metadata"]["description"] = None  # Set description to null
        payload["metadata"]["name"] = "ravish-test-null-description"
        
        # When - the user sends a POST request to "/policies" with the payload
        response = self.session.post(
            f"{self.API_BASE_URL}{self.ENDPOINT}",
            json=payload,
            headers=self.headers,
            verify=False
        )
        
        # Debug output
        print(f"\n[DEBUG] Response Status: {response.status_code}")
        print(f"[DEBUG] Response Body: {response.text[:500] if response.text else 'Empty'}")
        
        # Then - the response status code should be 400
        assert response.status_code == 400, \
            f"Expected 400 for null description, got {response.status_code}: {response.text}"
        
        # And - the response should contain an error message about invalid description
        if response.headers.get('content-type', '').startswith('application/json'):
            response_data = response.json()
            error_message = str(response_data).lower()
            assert any(keyword in error_message for keyword in ['description', 'null', 'required', 'invalid', 'error']), \
                f"Error message should mention description issue: {response.text}"
            print(f"[DEBUG] Error response as expected: {json.dumps(response_data, indent=2)[:500]}")


# if __name__ == "__main__":
#     testobj = TestCreatePolicyDescriptionValidation()
#     # Initialize session manually (normally done by pytest fixture)
#     testobj.session = requests.Session()
    
#     # Get token
#     token = testobj._get_access_token()
#     print(f"Access token: {token}")
    
#     # Clean up
#     testobj.session.close()

