"""API Test module for Create Policy - Description Field Validation.

Auto-generated by AI Test Case Generator.
Target API: https://uapautomation-uap.cyberark-everest-pre-prod.cloud/api
Authentication: OAuth2 token from CyberArk Identity
"""

import pytest
import requests
import json


class TestCreatePolicyDescriptionValidation:
    """API Test cases for Create Policy - Description Field Validation."""
    
    # Token API Configuration
    TOKEN_URL = "https://aog5018.id.integration-cyberark.cloud/oauth2/token/scadev"
    TOKEN_USERNAME = "serviceuserapr@cyberark.cloud.43204"
    TOKEN_PASSWORD = "Cyber@123"
    
    # Policy API Configuration
    API_BASE_URL = "https://uapautomation-uap.cyberark-everest-pre-prod.cloud/api"
    ENDPOINT = "/policies"
    
    @pytest.fixture(autouse=True)
    def setup(self):
        """Setup for each test - obtain OAuth2 token."""
        self.session = requests.Session()
        
        # Get OAuth2 token
        self.access_token = self._get_access_token()
        
        # Set headers with Bearer token
        self.headers = {
            "Content-Type": "application/json",
            "Accept": "application/json",
            "Authorization": f"Bearer {self.access_token}"
        }
        
        yield
        self.session.close()
    
    def _get_access_token(self) -> str:
        """Obtain OAuth2 access token from CyberArk Identity.
        
        Returns:
            Access token string
        """
        token_payload = {
            "grant_type": "client_credentials",
            "scope": "full"
        }
        
        # Use Basic Auth for token request
        response = self.session.post(
            self.TOKEN_URL,
            data=token_payload,
            auth=(self.TOKEN_USERNAME, self.TOKEN_PASSWORD),
            headers={"Content-Type": "application/x-www-form-urlencoded"}
        )
        
        if response.status_code != 200:
            raise Exception(f"Failed to get token: {response.status_code} - {response.text}")
        
        token_data = response.json()
        return token_data.get("access_token")
    
    def get_base_payload(self) -> dict:
        """Return the base payload for Create Policy API."""
        return {
            "metadata": {
                "policyId": None,
                "name": "test",
                "description": "test",
                "status": {
                    "status": "Active",
                    "statusCode": None,
                    "statusDescription": None
                },
                "timeFrame": {
                    "fromTime": None,
                    "toTime": None
                },
                "policyEntitlement": {
                    "targetCategory": "Cloud console",
                    "locationType": "Azure",
                    "policyType": "Recurring"
                },
                "policyTags": ["test"],
                "timeZone": "Asia/Calcutta"
            },
            "conditions": {
                "accessWindow": {
                    "timeZone": "Asia/Calcutta",
                    "daysOfTheWeek": [0, 1, 2, 3, 4, 5, 6]
                },
                "maxSessionDuration": 1
            },
            "targets": {
                "targets": [
                    {
                        "roleId": "/providers/Microsoft.Authorization/roleDefinitions/c2f4ef07-c644-48eb-af81-4b1b4947fb11",
                        "workspaceId": "providers/Microsoft.Management/managementGroups/c5a5de91-6a2f-467e-aefa-b3f62876ec6a",
                        "roleName": "AcrDelete",
                        "workspaceName": "Tenant Root Group",
                        "description": "acr delete",
                        "orgId": "c5a5de91-6a2f-467e-aefa-b3f62876ec6a",
                        "workspaceType": "management_group",
                        "roleType": 0
                    }
                ]
            },
            "principals": [
                {
                    "id": "c2c7bcc6-9560-44e0-8dff-5be221cd37ee",
                    "name": "adi_moldavski@cyberark.cloud.296894",
                    "displayName": "adi_moldavski",
                    "sourceDirectoryName": "CyberArk Cloud Directory",
                    "sourceDirectoryId": "09B9A9B0-6CE8-465F-AB03-65766D33B05E",
                    "type": "USER",
                    "role": 1
                }
            ],
            "delegation_classification": "Unrestricted"
        }
    
    # ==================== POSITIVE TEST CASE ====================
    
    @pytest.mark.positive
    def test_create_policy_with_valid_description_string(self):
        """Verify policy creation succeeds with valid string description under 200 chars.
        
        Steps:
        1. Obtain OAuth2 token from CyberArk Identity
        2. Prepare policy payload with valid description (string, < 200 chars)
        3. Send POST request to /policies endpoint
        4. Verify response status is 200 or 201
        5. Verify response contains policy details
        """
        # Arrange
        payload = self.get_base_payload()
        payload["metadata"]["description"] = "Valid test policy description for automation testing"
        payload["metadata"]["name"] = "AutoTest_ValidDescription"
        
        # Act
        response = self.session.post(
            f"{self.API_BASE_URL}{self.ENDPOINT}",
            json=payload,
            headers=self.headers
        )
        
        # Assert
        print(f"\n[DEBUG] Response Status: {response.status_code}")
        print(f"[DEBUG] Response Body: {response.text[:500] if response.text else 'Empty'}")
        
        assert response.status_code in [200, 201], \
            f"Expected 200/201, got {response.status_code}: {response.text}"
        
        # Verify response contains expected data
        if response.headers.get('content-type', '').startswith('application/json'):
            response_data = response.json()
            print(f"[DEBUG] Policy created: {json.dumps(response_data, indent=2)[:500]}")
