"""API Test module for Create Policy API - Description Field Validation.

Auto-generated by AI Test Case Generator.
API Endpoint: POST https://uapautomation-uap.cyberark-everest-pre-prod.cloud/api/policies

Authentication Flow:
1. Obtain OAuth2 token from CyberArk Identity
2. Use Bearer token for API requests
"""

import pytest
import requests
import json
import urllib3

# Suppress SSL warnings
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


class TestCreatePolicyDescriptionValidation:
    """API Test cases for Create Policy - Description Field Validation."""
    
    # Token API Configuration
    TOKEN_URL = "https://aog5018.id.integration-cyberark.cloud/oauth2/token/scadev"
    TOKEN_USERNAME = "serviceuserapr@cyberark.cloud.43204"
    TOKEN_PASSWORD = "Cyber@123"
    
    # Policy API Configuration
    API_BASE_URL = "https://uapautomation-uap.cyberark-everest-pre-prod.cloud/api"
    ENDPOINT = "/policies"
    
    @pytest.fixture(autouse=True)
    def setup(self):
        """Setup for each test - obtain OAuth2 token."""
        self.session = requests.Session()
        self.session.verify = False
        
        # Get OAuth2 token
        self.access_token = self._get_access_token()
        
        # Set headers with Bearer token
        self.headers = {
            "Content-Type": "application/json",
            "Accept": "application/json",
            "Authorization": f"Bearer {self.access_token}"
        }
        
        yield
        self.session.close()
    
    def _get_access_token(self) -> str:
        """Obtain OAuth2 access token from CyberArk Identity.
        
        Token Body: {"grant_type": "client_credentials", "scope": "full"}
        
        Returns:
            Access token string
        """
        token_payload = {
            "grant_type": "client_credentials",
            "scope": "full"
        }
        
        response = self.session.post(
            self.TOKEN_URL,
            data=token_payload,
            auth=(self.TOKEN_USERNAME, self.TOKEN_PASSWORD),
            headers={"Content-Type": "application/x-www-form-urlencoded"},
            verify=False
        )
        
        if response.status_code != 200:
            pytest.fail(f"Failed to get token: {response.status_code} - {response.text}")
        
        token_data = response.json()
        return token_data.get("access_token")
    
    def get_base_payload(self) -> dict:
        """Return the base payload for Create Policy API."""
        return {
            "metadata": {
                "policyId": None,
                "name": "ravish-test-31",
                "description": "test",
                "status": {
                    "status": "Active",
                    "statusCode": None,
                    "statusDescription": None
                },
                "timeFrame": {
                    "fromTime": None,
                    "toTime": None
                },
                "policyEntitlement": {
                    "targetCategory": "Cloud console",
                    "locationType": "AWS",
                    "policyType": "Recurring"
                },
                "policyTags": [],
                "timeZone": "Asia/Calcutta"
            },
            "conditions": {
                "accessWindow": {
                    "timeZone": "Asia/Calcutta",
                    "daysOfTheWeek": [0, 1, 2, 3, 4, 5, 6]
                },
                "maxSessionDuration": 1
            },
            "targets": {
                "targets": [
                    {
                        "roleId": "arn:aws:iam::103162528131:role/AWXAccessRoleAccess",
                        "workspaceId": "103162528131",
                        "roleName": "AWXAccessRoleAccess",
                        "workspaceName": "DEV1",
                        "description": None
                    }
                ]
            },
            "principals": [
                {
                    "id": "d4c322fc-931c-4c1c-9a40-2e8bae17f494",
                    "name": "au_tony_1_sca_uap@cyberark.cloud.43204",
                    "displayName": "au_tony_1_sca_uap",
                    "sourceDirectoryName": "CyberArk Cloud Directory",
                    "sourceDirectoryId": "09B9A9B0-6CE8-465F-AB03-65766D33B05E",
                    "type": "USER",
                    "role": 1
                }
            ],
            "delegation_classification": "Unrestricted"
        }
    
    # ==================== POSITIVE TEST CASE ====================
    
    @pytest.mark.positive
    @pytest.mark.description
    @pytest.mark.validation
    def test_successfully_create_policy_with_valid_description_under_200_chars(self):
        """Verify policy creation succeeds with valid string description under 200 chars.
        
        Scenario: Successfully create policy with valid description (string, under 200 chars)
          Given the user obtains OAuth2 token from the token endpoint
          And the policy payload has description "Valid test policy description"
          When the user sends a POST request to "/policies" with valid payload
          Then the response status code should be 200 or 201
          And the response should contain the created policy details
        """
        # Given - the policy payload has description "Valid test policy description"
        payload = self.get_base_payload()
        payload["metadata"]["description"] = "Valid test policy description"
        # Use unique policy name for each test run
        import time
        payload["metadata"]["name"] = f"ravish-test-valid-{int(time.time())}"
        
        # When - the user sends a POST request to "/policies" with valid payload
        response = self.session.post(
            f"{self.API_BASE_URL}{self.ENDPOINT}",
            json=payload,
            headers=self.headers,
            verify=False
        )
        
        # Debug output
        print(f"\n[DEBUG] Response Status: {response.status_code}")
        print(f"[DEBUG] Response Body: {response.text[:500] if response.text else 'Empty'}")
        
        # Then - the response status code should be 200 or 201
        assert response.status_code in [200, 201], \
            f"Expected 200/201, got {response.status_code}: {response.text}"
        
        # And - the response should contain the created policy details
        if response.headers.get('content-type', '').startswith('application/json'):
            response_data = response.json()
            assert response_data is not None, "Response should contain policy data"
            print(f"[DEBUG] Policy created successfully: {json.dumps(response_data, indent=2)[:500]}")

    # ==================== NEGATIVE TEST CASE - 200 CHAR LIMIT ====================
    
    @pytest.mark.negative
    @pytest.mark.description
    @pytest.mark.length_validation
    def test_fail_to_create_policy_when_description_exceeds_200_characters(self):
        """Verify policy creation fails when description exceeds 200 characters.
        
        Scenario: Fail to create policy when description exceeds 200 characters
          Given the user obtains OAuth2 token from the token endpoint
          And the policy payload has description with more than 200 characters
          When the user sends a POST request to "/policies" with the payload
          Then the response status code should be 400
          And the response should contain an error message about description length
          And no policy should be created
        """
        # Given - the policy payload has description with more than 200 characters
        payload = self.get_base_payload()
        # Generate a description with 201 characters (exceeds 200 limit)
        long_description = "A" * 201
        payload["metadata"]["description"] = long_description
        import time
        payload["metadata"]["name"] = f"ravish-test-long-desc-{int(time.time())}"
        
        # When - the user sends a POST request to "/policies" with the payload
        response = self.session.post(
            f"{self.API_BASE_URL}{self.ENDPOINT}",
            json=payload,
            headers=self.headers,
            verify=False
        )
        
        # Debug output
        print(f"\n[DEBUG] Description length: {len(long_description)} characters")
        print(f"[DEBUG] Response Status: {response.status_code}")
        print(f"[DEBUG] Response Body: {response.text[:500] if response.text else 'Empty'}")
        
        # Then - the response status code should be 400
        assert response.status_code == 400, \
            f"Expected 400 for description exceeding 200 chars, got {response.status_code}: {response.text}"
        
        # And - the response should contain an error message about description length
        if response.headers.get('content-type', '').startswith('application/json'):
            response_data = response.json()
            error_message = str(response_data).lower()
            assert any(keyword in error_message for keyword in ['description', 'length', 'character', 'max', 'limit', 'long', 'exceed', 'invalid', 'error']), \
                f"Error message should mention description length issue: {response.text}"
            print(f"[DEBUG] Error response as expected: {json.dumps(response_data, indent=2)[:500]}")
